version: '3.9'

services:
  app_server:
    container_name: file-uploader
    image: app_server:1.0.0
    build: .
    command: npm run start:dev
    env_file: production.env
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database
  database:
    container_name: app_mysql
    image: mysql
    env_file: production.env
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - '3306:3306'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:

volumes:
  db:
    driver: local