version: '3.9'

services:
  app_server:
    container_name: file-uploader
    image: app_server:1.0.0
    build: .
    command: npm run start:dev
    env_file: production.env
    ports:
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  app-network: